import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import Navbar from "./Components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
			<html lang="en">
				<body className="bg-black no-scrollbar overflow-y-scroll overflow-x-hidden">
					<MantineProvider>
						<div className="h-full bg-main-background-image bg-cover bg-fixed ">
							<div className="h-full bg-black bg-opacity-70">
								<div className="fixed w-full h-[80px] z-50 backdrop-blur-[2px]">
									<Navbar />
								</div>
								<div className="pt-[80px]">{children}</div>
								<div className="h-[200px]">footer</div>
							</div>
						</div>
					</MantineProvider>
				</body>
			</html>
		);
}
