import type { Metadata } from "next";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import Navbar from "./Components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black no-scrollbar overflow-y-scroll overflow-x-hidden">
        <MantineProvider>
          <div className="h-full bg-main-background-image bg-cover bg-fixed ">
            <div className="h-full bg-black bg-opacity-70">
              <Navbar />
              {children}
            </div>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
